// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXrRLgzHzYcxlJxN8xL8rIDlhxu4VJauw',
    appId: '1:120460892300:web:9f99ddd01f04d65c7d03a9',
    messagingSenderId: '120460892300',
    projectId: 'flutter-fcm-3e805',
    authDomain: 'flutter-fcm-3e805.firebaseapp.com',
    storageBucket: 'flutter-fcm-3e805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6RaW1T0m-vgBRIC8-aJTdLeEzMJMQcRE',
    appId: '1:120460892300:android:bd8592a25d1568827d03a9',
    messagingSenderId: '120460892300',
    projectId: 'flutter-fcm-3e805',
    storageBucket: 'flutter-fcm-3e805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC6KoCg3b0SnJwGVfibz1yn2fTkAysCM',
    appId: '1:120460892300:ios:a65dc4b14f41c38e7d03a9',
    messagingSenderId: '120460892300',
    projectId: 'flutter-fcm-3e805',
    storageBucket: 'flutter-fcm-3e805.appspot.com',
    androidClientId: '120460892300-40rv1qiu99tc6g754jssul3gluag9bk9.apps.googleusercontent.com',
    iosClientId: '120460892300-jkgplk5s3poq6n4617fqpkvb41kta211.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );
}
